services:
  mcp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - mcp-node-modules:/workspaces/app/node_modules
    command: sleep infinity
    depends_on:
      - redmine
      - db
  redmine:
    image: redmine:latest
    restart: unless-stopped
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - redmine-files:/usr/src/redmine/files
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: redmine
volumes:
  mcp-node-modules:
  redmine-files:
  postgres-data:
